# Site settings
title: The No-Pass Filter
email: bitbyt3r@bitbyt3r.net
description: > # this means to ignore newlines until "baseurl:"
  Discussion about Electronics, Linux, and Life. Not necessarily in that 
  order.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitbyt3r.net" # the base hostname & protocol for your site
twitter_username: bitbyt3r
github_username:  bitbyt3r

# Build settings
markdown: kramdown
